# Generated by Django 5.1.6 on 2025-02-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Melanoma', 'Melanoma'), ('Gastrectomy', 'Gastrectomy'), ('Whipple', 'Whipple')], max_length=20)),
                ('date', models.DateTimeField()),
                ('length_of_stay', models.IntegerField()),
                ('complications', models.BooleanField(default=False)),
                ('t_stage', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4')], max_length=2)),
                ('p_stage', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3)),
                ('procedure_time', models.FloatField()),
                ('surgeon', models.ForeignKey(on_delete=models.deletion.CASCADE, to='dashboard.surgeon')),
            ],
        ),
    ]
