# Generated by Django 5.1.7 on 2025-03-16 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeonRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('lower_ci', models.FloatField()),
                ('upper_ci', models.FloatField()),
                ('n_cases', models.IntegerField()),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.surgeon')),
            ],
            options={
                'indexes': [models.Index(fields=['surgeon', 'model_id'], name='dashboard_s_surgeon_987a3d_idx')],
            },
        ),
    ]
