# Generated by Django 5.1.7 on 2025-03-16 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sample_data'),
        ('dashboard', '0002_surgeonrate'),
    ]

    operations = [
    ]
